services:
  mariadb:
    image: mariadb:11.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  backend-app:
    build:
        context: ./backend
        dockerfile: Dockerfile
    restart: always
    container_name: backend-flask-app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL_PREFIX}${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    env_file:
      - .env
    ports:
      - "${BACKEND_OUTPORT}:5001"

  frontend-app:
    image: node:20-alpine
    container_name: frontend-app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
        - "${FRONTEND_OUTPORT}:3000"
    command: sh -c "npm install && npm run dev-docker"
    environment:
        - NODE_ENV=development
